services:
  - type: web
    name: bank-analyzer-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: USDT_WALLET_ADDRESS
        sync: false
      - key: USDT_NETWORK
        value: tron
      - key: USDT_PRICE
        value: "5"
      - key: TRONGRID_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
